feat: Added nextjs tutorial page
digitalfortress-dev/foundation pull request #17
Opened 2024-06-21 09:56 UTC by kinhdev24

2024-06-21 11:38 UTC, Quynh-Nguyen requested changes

2024-06-21 11:38 UTC, Quynh-Nguyen commented on pages/development/coding-conventions/Nextjs/structure.mdx
@kinhdev24 We shouldn't show the source code structure in the coding-conventions folder, Kinh

2024-06-21 11:38 UTC, Quynh-Nguyen commented on pages/development/coding-conventions/Nextjs/structure.mdx
It should be on platform -> web -> source code structure

2024-06-24 02:16 UTC, kinhdev24 commented on pages/development/coding-conventions/Nextjs/structure.mdx
okay, I will update it soon. Thanks for your feedback, anh Quynh

2025-03-04 04:07 UTC, Quynh-Nguyen commented on pages/development/coding-conventions/Nextjs/structure.mdx
@kinhdev24 Can you please help me update this, bro

2025-05-27 17:19 UTC, closed without merging